server:
  port: 8888
  tomcat:
    accesslog:
      enabled: true
      directory: logs
    basedir: ${HOME}/tomcat
spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/git/spring/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
          